### ISSUE TITLE
How to Import Pages from a Website Built with `CodeRed CMS` Into a Company's CMS Based on `CodeRed CMS`?

### ISSUE THREAD

**Issue by FilipWozniak** [wagtail/wagtail-transfer#110]
A few months ago, the company I work for, have forked `CodeRed CMS`. We created our own CMS system based on `CodeRed CMS` (version `0.20`, strictly speaking).

The key difference is that `CodeRed CMS` is a full Django Project, while our CMS does not take over `Wagtail` project, as a result of which we may install it as another (separate and independent) application. Similarly to `CodeRed CMS`, it also provides reusable pages like `ArticleIndex`, `Article` or `WebPage` (extended with additional functionality, of course). 

The biggest (and most significant) difference between `CodeRed CMS` and our CMS is that we have redefined `root` page, so all the child pages inherits not from the `wagtailcore.page` or `coderedcms.coderedpage`, but from `cms.cmspage`. 

The point is, that we still maintain a few websites based on `CodeRed CMS`, and we would like to transfer all the content from `CodeRed CMS` to our CMS (and not manually, because we have hundreds of pages full of content).

So I have two questions. 

First of all - whether that is even feasible with [`wagtail-transfer`](https://github.com/wagtail/wagtail-transfer)? I've tried and got the following error (after clicking on "Import Page" button):

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/64541581/157714711-78c55b3f-21ee-40c7-9001-1edfe2f242a1.png">

<img width=70% height=70% alt="image" src="https://user-images.githubusercontent.com/64541581/157714963-6d2def3f-c477-4f7f-ab58-42266cc23f7c.png">

I even tried to force [`wagtail-transfer`](https://github.com/wagtail/wagtail-transfer) to ignore `coderedcms.coderedpage` model, but, so far, unsuccessfully.

```python
WAGTAILTRANSFER_NO_FOLLOW_MODELS = ['coderedcms.coderedpage']
```

Secondly, if it's not possible, then what's the easiest way to migrate from `CodeRed CMS` to company's CMS in this particular case?

**Comment by gasman** [comment]
Hi @FilipWozniak,
No, migrating between different systems is outside the scope of wagtail-transfer. wagtail-transfer is for transferring data between multiple instances of a site, all of which are configured identically.
