### ISSUE TITLE
Expected UI issues with Wagtail 3.0 release

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail-transfer#113]
The [Wagtail 3.0 first release candidate](https://github.com/wagtail/wagtail/discussions/8362) is out. There are large UI changes in this release, for which we have [reviewed expected breakage in third-party UI customisations](https://github.com/wagtail/wagtail/discussions/7739#discussioncomment-2615089).

This is beyond what we do with our normal breaking changes policy, since the majority of those changes are on parts of Wagtail that haven’t been publicly supported / documented in any way. To make sure this goes smoothly anyway, I’m here to provide an advance notice of what we’re aware of with this specific package 🙂 

In the case of wagtail-transfer here are the issues we’re aware of

## Uppercase text

The majority of the Wagtail admin UI [no longer uses uppercase text](https://github.com/wagtail/wagtail/issues/7624), to improve readability. The exception is the page status (live, draft, etc.). Suggested actions:

- Remove all usage of uppercase text in the CMS, except for page status.
- Aside from CSS, the utility classes `u-text-transform-uppercase` and `label-uppercase` no longer exist and shouldn’t be used anymore.

```text
wagtail/wagtail/wagtail-transfer/wagtail_transfer/static/wagtail_transfer/css/transfer-styles.css
31:	text-transform: uppercase;
```

## Core templates reuse

This needs review depending on what the customisations are exactly. There may be nothing to changeh ere.

```text
wagtail/wagtail/wagtail-transfer/wagtail_transfer/templates/wagtail_transfer/choose_page.html
1:{% extends "wagtailadmin/base.html" %}
7:    {% include "wagtailadmin/pages/_editor_css.html" %}
19:    {% include "wagtailadmin/shared/header.html" with title=title_str icon="doc-empty-inverse" %}
```

**Comment by gasman** [comment]
Addressed in #118. Button styles here were already pretty screwy in older Wagtail versions, but the lowercase text is one thing it did get right :-)
