### ISSUE TITLE
Django 4.0 compatability

### ISSUE THREAD

**Issue by bmoe872** [wagtail/wagtail-transfer#115]
When trying to upgrade our project to Django 4.X we're getting errors around importing `url` from `django.conf.urls` which is being imported in the admin view set for wagtail transfer. 

There may be other issues with Django 4.0 as well, but that was the first I came across when doing the upgrade.

**Comment by gasman** [comment]
Thanks for reporting! This is fixed on main by #104 - will get a new release out with this and other fixes.
