### ISSUE TITLE
TemplateDoesNotExist wagtail_transfer/choose_page.html

### ISSUE THREAD

**Issue by cyface** [wagtail/wagtail-transfer#20]
Hello! I hooked this up, and confirmed that I have `wagtail_transfer` in my `installed_apps`, but when I try the "Import Content" menu item, I get `TemplateDoesNotExist wagtail_transfer/choose_page.html`.

I see those templates in the master source code, so I am wondering if my CICD install from master needs to be configured differently.

This is what I am currently doing in my requirements.txt:

git+git://github.com/wagtail/wagtail-transfer.git@master#wagtail-transfer

Do you have any suggestion on how to set it up so that the template folder gets installed?

**Comment by kaedroho** [comment]
We need to add a `MANIFEST.in` file. For example https://github.com/wagtail/wagtail-localize/commit/51f006abdbce7603cd9e4ea48f9c23793763153c

**Comment by gasman** [comment]
Fixed in 25047e936e15c978697a0c6c129d9cd78a78bc1b.
