### ISSUE TITLE
Does not work with python3.5

### ISSUE THREAD

**Issue by pcliupc** [wagtail/wagtail-transfer#99]
File "/venv/lib/python3.5/site-packages/wagtail_transfer/views.py", line 204
response = requests.get(f"{base_url}{path}?{message}&digest={digest}", headers={
                                                                ^
SyntaxError: invalid syntax

**Comment by gasman** [comment]
Python 3.5 is [well out of support now](https://endoflife.date/python), so I've updated the package metadata in ce03a9ca7bcd66432d8e7f8bcfc96d47672dd5d7 to mark it as incompatible.
